CREATE DATABASE IF NOT EXISTS Student_db;
USE Student_db;
CREATE TABLE IF NOT EXISTS Students(
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(100),
    roll INT(100),
    class VARCHAR(20),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
)